print(ord('a'))
print(ord('z'))
print('-' * 0)
print(1*'-')
print('' in 'alphabet')
message = "Mary has 21 little sheep"
print(message.split())
print('Analog' < 'analog')
print(str(None) == None)
print(type(None))
print(type('None'))
print('FEDCBA'[-3:])
print('AXBYCZ'[::-2])
print('Al'*2)
print(2*'Al')
print(10 != '1' + '0')
